/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdiappgui;

import java.io.PrintWriter;
import javax.swing.JFrame;

/**
 *
 * @author °°Edgars Sinkevičs°°
 */

public class mainWindowSinkevics extends javax.swing.JFrame {

    /**
     * Creates new form mainWindowSinkevics
     */
    public mainWindowSinkevics() {
           initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TestsSinkevics = new javax.swing.JDialog();
        jPanelTest1 = new javax.swing.JPanel();
        Jautajums1 = new javax.swing.JLabel();
        answer1 = new javax.swing.JRadioButton();
        answer2 = new javax.swing.JRadioButton();
        answer3 = new javax.swing.JRadioButton();
        Jautajums2 = new javax.swing.JLabel();
        answerBox1 = new javax.swing.JCheckBox();
        answerBox2 = new javax.swing.JCheckBox();
        answerBox3 = new javax.swing.JCheckBox();
        Jautajums3 = new javax.swing.JLabel();
        TextAnswer1 = new javax.swing.JTextField();
        Jautajums4 = new javax.swing.JLabel();
        ComboAnswer1 = new javax.swing.JComboBox<>();
        Jautajums5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jList2 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Pabeigt = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        RegisterForm = new javax.swing.JDialog();
        registr = new javax.swing.JPanel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        Password1 = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        RegisterButton = new javax.swing.JButton();
        Login = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        yourusername = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        Atbildes = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();

        jPanelTest1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Test", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24))); // NOI18N

        Jautajums1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jautajums1.setText("Kurā valstī atrodas Eifeļa tornis?");

        buttonGroup1.add(answer1);
        answer1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answer1.setText("Latvija");

        buttonGroup1.add(answer2);
        answer2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answer2.setText("Francija");
        answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(answer3);
        answer3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answer3.setText("Vācija");

        Jautajums2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jautajums2.setText("Kurā pilsētā atrodas Brīvības statuja?");

        answerBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answerBox1.setText("Florida");
        answerBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBox1ActionPerformed(evt);
            }
        });

        answerBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answerBox2.setText("Washington");
        answerBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBox2ActionPerformed(evt);
            }
        });

        answerBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answerBox3.setText("New York");

        Jautajums3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jautajums3.setText("Cik metrus ir visaugstākā ēka pasaulē?");

        TextAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAnswer1ActionPerformed(evt);
            }
        });

        Jautajums4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jautajums4.setText("Kurā gadā Latvijā tika atklāts Brīvības piemineklis?");

        ComboAnswer1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboAnswer1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1946", "1889", "1790", "1935" }));

        Jautajums5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jautajums5.setText("Cik torņu ir Maskavas kremlī?");

        jList1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "28", "10", "15", "20", "80" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cik garš ķīnas mūris?");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("21 196");

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("11 633");

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setText("15 458");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Kurā valstī ir lielākais tilts?");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kurā valstī lielākā pilsēta pasaulē ?");

        jList2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "USA", "Brazilijā", "Latvijā", "Japāna", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Kura pilsēta atrodas Kristus Pestītājs statuja?");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("Rīga");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2.setText("Riodežaneiro");

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox3.setText("New Yorka");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Kurā pilsētā atrodas Heopsa piramīdas?");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tokija", "Rīga", "Kaira", "Pariže" }));

        javax.swing.GroupLayout jPanelTest1Layout = new javax.swing.GroupLayout(jPanelTest1);
        jPanelTest1.setLayout(jPanelTest1Layout);
        jPanelTest1Layout.setHorizontalGroup(
            jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTest1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answer2)
                    .addComponent(answer1)
                    .addComponent(answer3)
                    .addComponent(Jautajums1)
                    .addComponent(Jautajums2)
                    .addComponent(answerBox1)
                    .addComponent(answerBox2)
                    .addComponent(answerBox3)
                    .addComponent(Jautajums3)
                    .addComponent(TextAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jautajums4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jautajums5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jList2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTest1Layout.setVerticalGroup(
            jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTest1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jautajums1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(answer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(answer2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(answer3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jautajums2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerBox1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTest1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerBox2)
                        .addGap(3, 3, 3)
                        .addComponent(answerBox3)
                        .addGap(18, 18, 18)
                        .addComponent(Jautajums3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTest1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jList2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jautajums4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTest1Layout.createSequentialGroup()
                        .addComponent(ComboAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(Jautajums5))
                    .addGroup(jPanelTest1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2)))
                .addGap(3, 3, 3)
                .addGroup(jPanelTest1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTest1Layout.createSequentialGroup()
                        .addComponent(jCheckBox3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        Pabeigt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pabeigt.setText("Pabeigt");
        Pabeigt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PabeigtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TestsSinkevicsLayout = new javax.swing.GroupLayout(TestsSinkevics.getContentPane());
        TestsSinkevics.getContentPane().setLayout(TestsSinkevicsLayout);
        TestsSinkevicsLayout.setHorizontalGroup(
            TestsSinkevicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestsSinkevicsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestsSinkevicsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pabeigt)
                .addGap(46, 46, 46))
        );
        TestsSinkevicsLayout.setVerticalGroup(
            TestsSinkevicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestsSinkevicsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pabeigt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        registr.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Register form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24))); // NOI18N

        FirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstName.setText("First name:");

        LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastName.setText("Last name:");

        Username1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Username1.setText("Username:");

        Password1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password1.setText("Password:");

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelLogin.setText("Click here to login");
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrLayout = new javax.swing.GroupLayout(registr);
        registr.setLayout(registrLayout);
        registrLayout.setHorizontalGroup(
            registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(registrLayout.createSequentialGroup()
                            .addComponent(FirstName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(registrLayout.createSequentialGroup()
                            .addComponent(LastName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField3)))
                    .addGroup(registrLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Password1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registrLayout.createSequentialGroup()
                        .addComponent(Username1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogin)
                .addGap(149, 149, 149))
        );
        registrLayout.setVerticalGroup(
            registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username1)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(registrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabelLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterFormLayout = new javax.swing.GroupLayout(RegisterForm.getContentPane());
        RegisterForm.getContentPane().setLayout(RegisterFormLayout);
        RegisterFormLayout.setHorizontalGroup(
            RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegisterFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterButton)
                .addGap(20, 20, 20))
        );
        RegisterFormLayout.setVerticalGroup(
            RegisterFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Window");
        setName("frameMain"); // NOI18N

        Login.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 24))); // NOI18N

        Username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Username.setText("Username:");

        yourusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourusernameActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.setText("Password:");

        jLabelRegister.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabelRegister.setText("Click here to create a new account ");
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        Atbildes.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Atbildes.setForeground(new java.awt.Color(204, 0, 153));
        Atbildes.setText("nav atbildets");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelRegister))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yourusername, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPassword)))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Atbildes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addComponent(Atbildes)
                .addGap(37, 37, 37)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(yourusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabelRegister))
        );

        ExitButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        LoginButton.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        LoginButton.setText("Login/Start test");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginButton)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton)
                    .addComponent(LoginButton)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(378, 325));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int TestRightAnswers = 0;   
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    try{
    String outputText = 
    "username: " + yourusername.getText() + "\n" + "password: " + jPassword.getText() + "\n" + "test: " + TestRightAnswers + " / 10";
                      
    PrintWriter fileWriter = new PrintWriter("txt/resultSinkevics.txt");
        for (String line : outputText.split("\\n")){
             fileWriter.println(line);
             }
             fileWriter.close();
        }catch(Exception ex){
        System.out.println(ex);
        }
     System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed

    yourusername.setText("");
    jPassword.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_answer2ActionPerformed

    private void answerBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBox1ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_answerBox1ActionPerformed

    private void answerBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBox2ActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_answerBox2ActionPerformed

    private void PabeigtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PabeigtActionPerformed
        TestRightAnswers = 0;

        //1 Jautajums
          if(answer2.isSelected()){
             TestRightAnswers++;
          }
               
        //2 Jautajums       
        if(answerBox3.isSelected()){
           TestRightAnswers++;
          }                        
                                                           
        //3 Jautajums
           if(TextAnswer1.getText().toLowerCase().equals("828")){
              TestRightAnswers++;
           }                           
           
        //4 Jautajums
          if(String.valueOf(ComboAnswer1.getSelectedItem()).equals("1935")){
             TestRightAnswers++;
          }
                
        //5 Jautajums
          if(jList1.isSelectedIndex(3)){
             TestRightAnswers++;  
          }
          
        //6 Jautajums
        if(jRadioButton1.isSelected()){
           TestRightAnswers++;
        }
        
        //7 Jautajums
        if(jTextField1.getText().toLowerCase().equals("Kina")){
           TestRightAnswers++;
        }
        
        //8 Jautajums
        if(jList2.isSelectedIndex(3)){
            TestRightAnswers++;
        }
        
        //9 Jautajums       
        if(jCheckBox2.isSelected()){
           TestRightAnswers++;     
        }
       
        //10 Jautajums
        if(String.valueOf(jComboBox1.getSelectedItem()).equals("Kaira")){
           TestRightAnswers++;    
        }
        
        System.out.println("Pareizās atbildes: " + TestRightAnswers + " / 10");       
        Atbildes.setText(TestRightAnswers + " / 10");
        TestsSinkevics.setVisible(false);
        setVisible(true);       
    }

    private void exitProgrammButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        try{
        String outputText = 
         "username: " + yourusername.getText() + "\n" + "password: " + jPassword.getText() + "\n" + "tests: " + TestRightAnswers + " / 10";
            
            PrintWriter fileWriter = new PrintWriter("txt/resultSinkevics.txt");
            for (String line : outputText.split("\\n")){
                 fileWriter.println(line);
            }
            fileWriter.close();
        }catch(Exception ex){
            System.out.println(ex);
        }
        System.exit(0);
    }//GEN-LAST:event_PabeigtActionPerformed

    private void TextAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAnswer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAnswer1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
    RegisterForm.setVisible(true);
    Login.setVisible(false);
    RegisterForm.setBounds(560,300,500,400); 
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
       //
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
    Login.setVisible(true);
    RegisterForm.setVisible(false);
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void yourusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourusernameActionPerformed
       //
    }//GEN-LAST:event_yourusernameActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
    TestsSinkevics.setVisible(true);
    TestsSinkevics.setBounds(460,150,820,720);
    Login.setVisible(true);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
      try{
        String outputText = 
         "Name: " + jTextField2.getText() + "\n" + "Surname: " + jTextField3.getText() + "\n" + "User: " + jTextField4.getText() + "\n"  +  "Password: " + jPasswordField1.getText() + "\n";
            
            PrintWriter fileWriter = new PrintWriter("txt/RegistrationSinkevics.txt");
            for (String line : outputText.split("\\n")){
                 fileWriter.println(line);                    
            }
            System.out.println("Reģistrācija ir veiksmīgi pabeigta!! "); 
             System.out.println(outputText); 
            fileWriter.close();
        }catch(Exception ex){
            System.out.println(ex);
        }
        RegisterForm.setVisible(false);
        Login.setVisible(true);;                                          
    }//GEN-LAST:event_RegisterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindowSinkevics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindowSinkevics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindowSinkevics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindowSinkevics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindowSinkevics().setVisible(true);
            }
        }
       );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atbildes;
    private javax.swing.JButton ClearButton;
    private javax.swing.JComboBox<String> ComboAnswer1;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel Jautajums1;
    private javax.swing.JLabel Jautajums2;
    private javax.swing.JLabel Jautajums3;
    private javax.swing.JLabel Jautajums4;
    private javax.swing.JLabel Jautajums5;
    private javax.swing.JLabel LastName;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton Pabeigt;
    private javax.swing.JLabel Password1;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JDialog RegisterForm;
    private javax.swing.JDialog TestsSinkevics;
    private javax.swing.JTextField TextAnswer1;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JRadioButton answer1;
    private javax.swing.JRadioButton answer2;
    private javax.swing.JRadioButton answer3;
    private javax.swing.JCheckBox answerBox1;
    private javax.swing.JCheckBox answerBox2;
    private javax.swing.JCheckBox answerBox3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanelTest1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel password;
    private javax.swing.JPanel registr;
    private javax.swing.JTextField yourusername;
    // End of variables declaration//GEN-END:variables
}
